### ISSUE TITLE
Add workflow for Windows Compilation

### ISSUE THREAD

**Issue by ugermann** [ugermann/ssplit-cpp#1]

**Comment by XapaJIaMnu** [comment]
@ugermann, how does one compile it on Windows. Notably, I'm struggling to get pcre2 version.

**Comment by ugermann** [comment]
I've never tried it, to be honest.

**Comment by ugermann** [comment]
Are you using Visual Studio on Windows? The quickest route to success would be, in my opinion, to compile pcre2 separately (e.g. by cloning https://github.com/kiyolee/pcre2-win-build) and then making sure cmake finds pcre2. A bit hacky, but since I haven't had any experience with compiling anything on Windows since the last millennium, it would take me some time to figure out an integrated solution.

**Comment by XapaJIaMnu** [comment]
I'm trying to use qt creator but experimenting with other ide /sdks package managers..

**Comment by ugermann** [comment]
Done.
