### ISSUE TITLE
Hard std::string_view despite typedef (to switch absl, std)

### ISSUE THREAD

**Issue by jerinphilip** [ugermann/ssplit-cpp#13]
https://github.com/ugermann/ssplit-cpp/blob/53877846639113d3cbc0eb7dac373453dd5cd0f3/src/ssplit/ssplit.cpp#L102

Since there is an attempt to support both absl and std (allowing CPP11 and CPP17), this is a bug?

**Comment by ugermann** [comment]
It was. Fixed now.
