### ISSUE TITLE
Correct Usage of ssplit-cpp

### ISSUE THREAD

**Issue by abhi-agg** [ugermann/ssplit-cpp#9]
@ugermann I compiled master branch of ssplit-cpp.

Running `./ssplit --help` gives following:
```
Sentence Splitter
Usage: ./ssplit [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  -p,--prefix-file TEXT:FILE  Path to prefix file.
  -P,--oppl                   Input is one paragraph per line (default: wrapped text)
  -t                          Test mode for wrapped text
```

This is different to what README's `Usage` section says:

`cat <text with one paragraph per line> | ssplit -p <path to nonbreaking_prefix file> -m<mode>`

Could we please resolve this?

In addition there are 4 test files in the [command folder](https://github.com/ugermann/ssplit-cpp/tree/master/src/command). Which one of them is the actual application?

**Comment by ugermann** [comment]
Should be fixed by now.
